apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-app
spec:
  selector:
    matchLabels:
      app: cli-app
  template:
    metadata:
      labels:
        app: cli-app
    spec:
      containers:
      - name: cli-app
        image: httpd:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cli-svc
spec:
  selector:
    app: cli-app
  ports:
  - port: 80
    targetPort: 80
