apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: utibeabasi6/argocd-code:v1.0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
spec:
  selector:
    app: argocd-app
  ports:
  - port: 8095
    targetPort: 5000
  type: LoadBalancer
